name: dpsg-wehr

services:
    website:
        image: dpsg-wehr:latest
        restart: unless-stopped
        deploy:
            mode: replicated
            replicas: 2
            update_config:
                order: start-first
                failure_action: rollback
                delay: 5s
        volumes:
            - ./public/generated:/usr/share/nginx/html/generated:ro
        networks:
            - proxy
        healthcheck:
            test: ['CMD-SHELL', 'curl -f http://127.0.0.1/ || exit 1']
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 5s
        labels:
            - 'traefik.enable=true'
            - 'traefik.docker.network=proxy'
            # HTTPS Router
            - 'traefik.http.routers.dpsg-website-secure.entrypoints=https'
            - 'traefik.http.routers.dpsg-website-secure.rule=Host(`www.dpsg-wehr.de`) || Host(`dpsg-wehr.de`)'
            - 'traefik.http.routers.dpsg-website-secure.tls=true'
            - 'traefik.http.routers.dpsg-website-secure.tls.certresolver=le_http'
            # Service Port
            - 'traefik.http.services.dpsg-website.loadbalancer.server.port=80'

    website-dev:
        image: dpsg-wehr:dev
        restart: unless-stopped
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                order: start-first
                failure_action: rollback
                delay: 5s
        volumes:
            - ./public/generated:/usr/share/nginx/html/generated:ro
        networks:
            - proxy
        healthcheck:
            test: ['CMD-SHELL', 'curl -f http://127.0.0.1/ || exit 1']
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 5s
        labels:
            - 'traefik.enable=true'
            - 'traefik.docker.network=proxy'
            # HTTPS Router
            - 'traefik.http.routers.dpsg-website-dev-secure.entrypoints=https'
            - 'traefik.http.routers.dpsg-website-dev-secure.rule=Host(`${DEV_DOMAIN:-dev.dpsg-wehr.de}`)'
            - 'traefik.http.routers.dpsg-website-dev-secure.tls=true'
            - 'traefik.http.routers.dpsg-website-dev-secure.tls.certresolver=le_http'
            # Authentik Forward-Auth Middleware
            - 'traefik.http.routers.dpsg-website-dev-secure.middlewares=${AUTHENTIK_MIDDLEWARE:-authentik@docker}'
            # Service Port
            - 'traefik.http.services.dpsg-website-dev.loadbalancer.server.port=80'

networks:
    proxy:
        external: true
