name: Tests & Checks

on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - main
            - dev

jobs:
    test:
        name: 🧪 Run Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 22

            - uses: pnpm/action-setup@v4
              with:
                  version: 10

            - name: 🧩 Install dependencies
              run: pnpm install --frozen-lockfile

            - name: ⚙️ Install Playwright Browsers
              run: pnpm exec playwright install --with-deps chromium

            - name: 🏗️ Build website
              env:
                  nextImageExportOptimizer_imageSizes: '16,64,128,256,384'
                  nextImageExportOptimizer_deviceSizes: '640,1080,1920'
              run: |
                  pnpm build
                  pnpm next-image-export-optimizer
                  node scripts/inline-css.mjs

            - name: 🚦 Run tests
              run: pnpm test:all
